const MAX_BLOG_NAME_LENGTH = 15
const MAX_BLOG_DESCRIPTION_LENGTH = 500
const MAX_BLOG_WEBSITE_URL_LENGTH = 100

export {
  MAX_BLOG_NAME_LENGTH,
  MAX_BLOG_DESCRIPTION_LENGTH,
  MAX_BLOG_WEBSITE_URL_LENGTH,
}
