const MAX_POST_TITLE_LENGTH = 30
const MAX_POST_SHORT_DESCRIPTION_LENGTH = 100
const MAX_POST_CONTENT_LENGTH = 1000

export {
  MAX_POST_TITLE_LENGTH,
  MAX_POST_SHORT_DESCRIPTION_LENGTH,
  MAX_POST_CONTENT_LENGTH,
}
